[package]
name = "unlinked-sim"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
unlinked-model = { path = "../unlinked-model" }
unlinked-matlab = { path = "../unlinked-matlab" }

[dev-dependencies]
serde_json = "1"
